version: "3"

services:
  nico-proxy:
    build: .
    restart: always
    links:
      - redis
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "25252:25252"
      - "25252:25252/udp"
    volumes:
      - /nico-proxy/nico-proxy:/nico-proxy
    command:
      sh -c "java -jar /opt/NicoVideoPlayForVRC-1.0-SNAPSHOT-all.jar"
  redis:
    restart: always
    image: redis:7-alpine
    volumes:
      - /nico-proxy/redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20